spring:
  application:
    name: toc
server:
  servlet:
    context-path: /toc
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.25.59:8080/eureka/
  instance:
    prefer-ip-address: true